TARGET: bitarr.o bitsop.o bitmap.o
bitarr.o: bitarr.c
	gcc -c bitarr.c -o bitarr.o
bitsop.o: bitsop.c
	gcc -c bitsop.c -o bitsop.o
bitmap.o: bitmap.c
	gcc -c bitmap.c -o bitmap.o
clean:
	rm bitarr.o
	rm bitsop.o
	rm bitmap.o
